### ISSUE TITLE
Roll icons overlap attributes

### ISSUE THREAD

**Issue by Bobloblah** [thehappyanarchist/foundryacks#15] opened 2020-09-24 15:19 UTC
**Is your feature request related to a problem? Please describe.**
The values for Alignment, Number Appearing, and Morale are overlapped by the dice icons for rolling against these values.

**Describe the solution you'd like**
Perhaps centre the values in their fields so that they can be seen without the "dice" roll icon overlapping them.

**Comment by thehappyanarchist** [comment] 2020-09-27 11:31
This is a slightly tricky CSS issue having to do with the way the icon is populated on the forms. Can be easily addressed I think, but what is a better place for the icon? The center of the field? The end? As is works fairly well and was intended to be formatted like this, you can always not hover on the field if it bothers you while typing.

**Comment by thehappyanarchist** [comment] 2020-10-25 23:05
Fixed in 0.7.1 release. Fields are now centered to not obscure text.

**Closed by thehappyanarchist** 2020-10-25 23:05 UTC
Labels: enhancement
